### ISSUE TITLE
[BUG] Pubsub not working between 2 instances of a simple application

### ISSUE THREAD

**Issue by NickTaylor-** [rs-ipfs/rust-ipfs#241] opened 2020-07-15 13:50 UTC
**Describe the bug**
I commented originally on https://github.com/rs-ipfs/rust-ipfs/issues/132#issuecomment-658218892, but basically I can't get 2 instances of a simple Rust program to communicate with eachother using pubsub. 

I feel like there is a reasonable chance there is also something wrong with my Rust code, as I am not great at Rust.

**To Reproduce**
```rust
use async_std::task;
use futures::StreamExt;
use ipfs::{IpfsOptions, Types, UninitializedIpfs};

fn main() {
    env_logger::init();
    let options = IpfsOptions::<Types>::default();

    task::block_on(async move {
        println!("IPFS options: {:?}", options);
        let (ipfs, future) = UninitializedIpfs::new(options).await.start().await.unwrap();
        task::spawn(future);

        // Subscribe
        let topic = "test1234".to_owned();
        let mut subscription = ipfs.pubsub_subscribe(topic.clone()).await.unwrap();
        
        ipfs.pubsub_publish(topic.clone(), vec![41, 41]).await.unwrap();
        while let Some(message) = subscription.next().await {
            println!("Got message: {:?}", message)
        }

        // Exit
        ipfs.exit_daemon().await;
    })
}
```

The above code was used to test on the `test1234` topic, sending some dummy bytes. The application is able to consume its own message (Client A):

```
IPFS options: IpfsOptions { ipfs_path: PathBuf { inner: "/Users/nicktaylor/.rust-ipfs" }, bootstrap: [("/ip4/104.131.131.82/tcp/4001", PeerId("QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ")), ("/ip4/104.236.179.241/tcp/4001", PeerId("QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM")), ("/ip4/104.236.76.40/tcp/4001", PeerId("QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64")), ("/ip4/128.199.219.111/tcp/4001", PeerId("QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu")), ("/ip4/178.62.158.247/tcp/4001", PeerId("QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd")), ("/ip6/2400:6180:0:d0::151:6001/tcp/4001", PeerId("QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu")), ("/ip6/2604:a880:1:20::203:d001/tcp/4001", PeerId("QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM")), ("/ip6/2604:a880:800:10::4a:5001/tcp/4001", PeerId("QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64")), ("/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001", PeerId("QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"))], keypair: Keypair::Ed25519, mdns: true }
Got message: PubsubMessage { source: PeerId("12D3KooWJXVxo6wY8T1CHuou3Nct4JrnYojRpnTnqKygv8tiymTp"), data: [41, 41], sequence_number: [176, 19, 137, 113, 220, 129, 183, 152, 104, 245, 121, 8, 46, 107, 141, 152, 255, 248, 3, 160], topics: ["test1234"] }
```

However, when a second instance (Client B) is started its only consumes its own message, with nothing being consumed by Client A:

```
IPFS options: IpfsOptions { ipfs_path: PathBuf { inner: "/Users/nicktaylor/.rust-ipfs" }, bootstrap: [("/ip4/104.131.131.82/tcp/4001", PeerId("QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ")), ("/ip4/104.236.179.241/tcp/4001", PeerId("QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM")), ("/ip4/104.236.76.40/tcp/4001", PeerId("QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64")), ("/ip4/128.199.219.111/tcp/4001", PeerId("QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu")), ("/ip4/178.62.158.247/tcp/4001", PeerId("QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd")), ("/ip6/2400:6180:0:d0::151:6001/tcp/4001", PeerId("QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu")), ("/ip6/2604:a880:1:20::203:d001/tcp/4001", PeerId("QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM")), ("/ip6/2604:a880:800:10::4a:5001/tcp/4001", PeerId("QmSoLV4Bbm51jM9C4gDYZQ9Cy3U6aXMJDAbzgu2fzaDs64")), ("/ip6/2a03:b0c0:0:1010::23:1001/tcp/4001", PeerId("QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd"))], keypair: Keypair::Ed25519, mdns: true }
Got message: PubsubMessage { source: PeerId("12D3KooWJXVxo6wY8T1CHuou3Nct4JrnYojRpnTnqKygv8tiymTp"), data: [41, 41], sequence_number: [194, 9, 29, 179, 181, 171, 142, 16, 229, 4, 162, 118, 44, 19, 7, 248, 3, 186, 49, 231], topics: ["test1234"] }
```

**Expected behavior**
Client A should see two `[41, 41]` messages, one from itself, one from Client B.

**Desktop:**
 - OS: macOS
 - Version: 10.15.5

**Comment by koivunej** [comment] 2020-07-15 14:07
Thanks for reproducer, it is looking good! Looking into this now.

**Comment by koivunej** [comment] 2020-07-15 14:28
I pushed the reproducer as an example at https://github.com/koivunej/rust-ipfs/tree/issue_241 so one can just  `cargo run --example issue_241`.

The cause for this issue is that the two nodes end up spinning up with the same node identity or the peerid. Confirm by printing the peerid as in [commit](https://github.com/koivunej/rust-ipfs/commit/7a598b65c9656289acff1002c1a396344953953c). As such, the two nodes will never be able to connect to each other. (This is, by design, or a feature of secio which [we currently use](https://github.com/rs-ipfs/rust-ipfs/blob/c257c88fafaf6617405ba4cb6c98feda3d868973/src/p2p/transport.rs#L24).)

With new keys generated on each run, like in [commit](https://github.com/koivunej/rust-ipfs/commit/fad56abdd3e34e1338c32893646052e9477bab1b) the two instances can find each other but are unlikely to see each others pubsub message. The pubsub message is not visible because it is published before any connections are made.

Regarding the reproducer, to understand more what is going on under the hood, you can add `RUST_LOG=trace,cargo=off` to the `cargo run --example issue_241`. It will spew a lot of tracing information but it will allow confirming that the nodes can now connect with the most recent change linked above.

So theres a mixture of issues here:

1. we have a lot of unfinished work with the `ipfs::IpfsOptions` and `ipfs::config::ConfigFile`
2. there is no "repo locking" which would had stopped the second instance from starting with the same config file
3. pubsub is not a reliable messaging transport

To see an example of pubsub being used to communicate between two nodes, please have a look at [`publish_between_two_nodes` in tests/pubsub.rs](https://github.com/rs-ipfs/rust-ipfs/blob/c257c88fafaf6617405ba4cb6c98feda3d868973/tests/pubsub.rs#L51).

**Comment by koivunej** [comment] 2020-07-16 09:25
> So theres a mixture of issues here:
> 
>     1. we have a lot of unfinished work with the `ipfs::IpfsOptions` and `ipfs::config::ConfigFile`
>     2. there is no "repo locking" which would had stopped the second instance from starting with the same config file
>     3. pubsub is not a reliable messaging transport

Created an issue already for (2) but I think (1) is more "scheduled to change" at least a bit when we get content discovery #10 and we'll at least update the bootstrap peer list (which is outdated and probably none of those peers can be connected to). This kind of reminds me of #105 which we'll need for proper bootstrap list handling.

@NickTaylor- do these actions at least shed some light on the original issue?

**Comment by koivunej** [comment] 2020-08-03 07:12
@NickTaylor- just pinging you again:

> NickTaylor- do these actions at least shed some light on the original issue?

**Comment by ljedrz** [comment] 2020-08-17 07:29
Updating the reproducer (the issues still apply):
```
use futures::StreamExt;
use ipfs::{Ipfs, IpfsOptions, Types, UninitializedIpfs};
use tokio::task;

#[tokio::main]
async fn main() {
    tracing_subscriber::fmt::init();
    let options = IpfsOptions::default();

    println!("IPFS options: {:?}", options);
    let (ipfs, future): (Ipfs<Types>, _) = UninitializedIpfs::new(options, None).await.start().await.unwrap();
    task::spawn(future);

    // Subscribe
    let topic = "test1234".to_owned();
    let mut subscription = ipfs.pubsub_subscribe(topic.clone()).await.unwrap();

    ipfs.pubsub_publish(topic.clone(), vec![41, 41]).await.unwrap();
    while let Some(message) = subscription.next().await {
        println!("Got message: {:?}", message)
    }

    // Exit
    ipfs.exit_daemon().await;
}
```

**Comment by koivunej** [comment] 2020-09-05 14:08
Assuming this was resolved and closing. Switching over to Gossipsub will be happening in the near future which will improve this.

**Closed by koivunej** 2020-09-05 14:08 UTC
Labels: bug
